
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8888
  servlet:
    context-path: /citycascade
spring:
  profiles:
       active: dev #激活dev配置

  resources:
   static-locations: classpath:/static/
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

